version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
  
  backend:
    image: tonysoprano228/go-server:latest
    depends_on:
      - postgres
    container_name: go-server
    ports:
      - 8080:8080
    